dataset:
  name:
    agnews
  path:
    pietrolesci/agnews
  label_feature:
    labels
  classes:
    0: world
    1: sports
    2: business
    3: sci/tech

pseudo_sample_prompt_template: |
  Suppose you are a jouranlist. There are now the news subcategories: world, sports, business, sci/tech. Please write a news article of about 200 words, so that its classification best fits the "{category}" category.

labeling_prompt_template: |
  You are a topic analysis tool for analysing news articles. Look at the following text:

  {text}

  What is the topic related to the text? Choose a topic from the following possible options:

  0) world
  1) sports
  2) business
  3) sci/tech

  Respond ONLY with the topic number and no other information.
